#!/bin/bash

# set this
export AKSSUB=k8s

# Change these if desired
export AKSRG=aks
export AKSNAME=aks

export AKSLOC=centralus
export AKSSIZE=Standard_D2s_v3

# Don't change this
export MCRG=MC_${AKSRG}_${AKSNAME}_${AKSLOC}

# setup an alias (optional)
alias k=kubectl

