#!/bin/bash

# this needs to be a unique DNS name 
export ACR_NAME=bartr

# Change these if desired
export AKSRG=aks
export ACRRG=acr
export ACR_SP=ACR_${ACR_NAME}
export AKSNAME=aks
export AKSLOC=centralus
export AKSSIZE=Standard_D2s_v3

# Don't change this
export MCRG=MC_${AKSRG}_${AKSNAME}_${AKSLOC}

# Read the SP password if it exists
if [ -f ~/.ssh/sp_pwd ]; then
	export SP_PWD=$(cat ~/.ssh/sp_pwd)
fi

# setup an alias (optional)
alias k=kubectl
