#!/bin/bash

. setenv

mkdir -p ~/.ssh

az group create --name $AKSRG --location $AKSLOC
az group create -n $ACRRG --location $AKSLOC

# Create service principal
az ad sp create-for-rbac --skip-assignment -n $ACR_SP -p $SP_PWD
APP_ID=$(az ad sp show --id http://$ACR_SP --query appId --output tsv)

# create Docker build VM
if [ -f ~/.ssh/id_rsa ]; then
    az vm create \
    --size standard_d2s_v3 \
    --nsg-rule SSH \
    --image Canonical:UbuntuServer:18.04-LTS:latest \
    -g aks \
    -n docker \
    --admin-username aks \
    --custom-data docker/startup.sh
else 
    az vm create \
    --size standard_d2s_v3 \
    --nsg-rule SSH \
    --image Canonical:UbuntuServer:18.04-LTS:latest \
    --generate-ssh-keys \
    -g aks \
    -n docker \
    --admin-username aks \
    --custom-data docker/startup.sh
fi

# create AKS cluster
# create AKS
az aks create -g $AKSRG \
-n $AKSNAME \
-c 3 \
-s $AKSSIZE \
--service-principal $APP_ID \
--client-secret $SP_PWD \
--no-wait

export DHOST=aks@`az network public-ip show -g aks -n dockerPublicIP --query [ipAddress] -o tsv`
echo $DHOST
