#!/bin/bash

mkdir -p ~/.ssh

. ~/setenv

# Create service principal
export AKS_PWD=$(az ad sp create-for-rbac --skip-assignment -n $AKS_SP --query password --output tsv)
echo $AKS_PWD > ~/.ssh/aks_pwd
export AKS_APP_ID=$(az ad sp show --id http://$AKS_SP --query appId --output tsv)

# create AKS cluster
az aks create -g $AKSRG \
-n $AKSNAME \
-c 3 \
-s $AKSSIZE \
--service-principal $AKS_APP_ID \
--client-secret $AKS_PWD \
--no-wait
