apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-gw
spec:
  selector:
    matchLabels:
      app: app-gw
  template:
    metadata:
      labels:
        app: app-gw
    spec:
      containers:
      - name: app-gw
        image: bartr/go-web-aks
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
